name = "beautiful-lyrics-reborn-server"
main = "src/index.ts"
compatibility_date = "2026-05-22"

[[routes]]
pattern = "lyrics.txw.qzz.io"
custom_domain = true

[[analytics_engine_datasets]]
binding = "STATS"
dataset = "lyrics_outcomes"

[observability.logs]
enabled = true
invocation_logs = true

[observability.traces]
enabled = false